### ISSUE TITLE
Improve load more as the current one does not work as intended

### ISSUE THREAD

**Issue by eivindroe** [eipe/mytentsite#30]

**Comment by eivindroe** [comment]
Maybe we can add information if there is more tent sites in result from api?
If yes - keep the button visible
If no - hide it

**Comment by eivindroe** [comment]
@petalst Does the current API return all photos or is it a limitation? If there is no limitation it is not necessary to have this button.

**Comment by petalst** [comment]
Pagination added on api. Limit set to 9
